version: '3.9'

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
    environment:
      - HOST_IP=${HOST_IP:-192.168.1.17}
    depends_on:
      - db
    networks:
      - appnet

  ws:
    build: ./web
    command: php /var/www/html/api/ws-server.php
    ports:
      - "8090:8090"
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db
    networks:
      - appnet

  db:
    image: mariadb:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: affinity
      MYSQL_USER: affinity
      MYSQL_PASSWORD: affinity
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - appnet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: affinity
      PMA_PASSWORD: affinity
    depends_on:
      - db
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
